// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsdnXxngwAotShP24I2ZYC5cY2dDBvcjs',
    appId: '1:309484748354:web:58daf43b2ca54e62e3b7db',
    messagingSenderId: '309484748354',
    projectId: 'sos-mulher-612e1',
    authDomain: 'sos-mulher-612e1.firebaseapp.com',
    storageBucket: 'sos-mulher-612e1.appspot.com',
    measurementId: 'G-JF2SGJEL1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACDtbPLaqMI3xIELmDjukEEXWWpI76Pps',
    appId: '1:309484748354:android:a2d64a97e8d254e7e3b7db',
    messagingSenderId: '309484748354',
    projectId: 'sos-mulher-612e1',
    storageBucket: 'sos-mulher-612e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEANESk7ftonV7EeM2GnCMT90QoFaKEK4',
    appId: '1:309484748354:ios:6b2ac7a5627f452fe3b7db',
    messagingSenderId: '309484748354',
    projectId: 'sos-mulher-612e1',
    storageBucket: 'sos-mulher-612e1.appspot.com',
    iosBundleId: 'com.example.painelSosMulher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEANESk7ftonV7EeM2GnCMT90QoFaKEK4',
    appId: '1:309484748354:ios:6b2ac7a5627f452fe3b7db',
    messagingSenderId: '309484748354',
    projectId: 'sos-mulher-612e1',
    storageBucket: 'sos-mulher-612e1.appspot.com',
    iosBundleId: 'com.example.painelSosMulher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsdnXxngwAotShP24I2ZYC5cY2dDBvcjs',
    appId: '1:309484748354:web:14e6ccf569b68ccde3b7db',
    messagingSenderId: '309484748354',
    projectId: 'sos-mulher-612e1',
    authDomain: 'sos-mulher-612e1.firebaseapp.com',
    storageBucket: 'sos-mulher-612e1.appspot.com',
    measurementId: 'G-QFZB237SE0',
  );
}
